// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyIdentityWeb.Models;

public partial class Benefit
{
    public int BenefitId { get; set; }

    public string BenefitName { get; set; }

    public virtual ICollection<BenefitEmployee> BenefitEmployees { get; set; } = new List<BenefitEmployee>();
}