// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyIdentityWeb.Models;

public partial class BenefitEmployee
{
    public int Id { get; set; }

    public int BenefitId { get; set; }

    public int? EmployeeId { get; set; }

    public virtual Benefit Benefit { get; set; }

    public virtual Employee Employee { get; set; }
}