// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyIdentityWeb.Models;

public partial class Employee
{
    public int EmployeeId { get; set; }

    public int DepartmentId { get; set; }

    public string EmployeeIdMasking { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public virtual ICollection<BenefitEmployee> BenefitEmployees { get; set; } = new List<BenefitEmployee>();

    public virtual Department Department { get; set; }
}